/**
 * Project-wide document layer (DESIGN §26).
 *
 * The problem it solves: every solution is a git worktree, so a document that
 * lives inside a worktree is copied the moment an experiment forks and stays
 * frozen in that copy. Shared knowledge — the charter, the roadmap, baseline
 * references, cross-cutting lessons — then diverges into one stale copy per
 * experiment, and the copies come back through merges.
 *
 * The rule this service enforces:
 *
 *   SHARED documents live ONLY in the project root's `docs/` directory, which
 *   `main` carries as a normal directory (so it is versioned, reviewable and
 *   diffable). Every solution worktree holds a single link `local/docs` →
 *   `../../docs`, so the same file is visible at either path with exactly one
 *   physical copy. Per-experiment notes stay inside the solution (they belong
 *   to the line of work), and their conclusions are promoted here.
 *
 * Because the link is a real symlink to the root, TWO things are guaranteed:
 *   1. root `docs/` is the single source of truth — editing through any
 *      solution writes the same file;
 *   2. `git add -A` inside a worktree skips the link entirely (git never
 *      descends into a symlinked directory), so shared docs cannot be
 *      duplicated into a solution branch by an ordinary checkpoint.
 *
 * Generated output (mirror of shared docs inside the worktree, per-solution
 * link repairs, promotion snapshots) goes to `docs/.dlab/`, which is
 * git-ignored: it is derived data, not knowledge.
 */

import {
  existsSync,
  lstatSync,
  type Stats,
  mkdirSync,
  readdirSync,
  readFileSync,
  readlinkSync,
  rmSync,
  statSync,
  symlinkSync,
  writeFileSync,
} from 'node:fs'
import { join, relative, resolve } from 'node:path'
import type { LabDeps } from './ports.js'
import type { Solution } from '@dsh-lab/shared'

export interface DocEntry {
  /** Path relative to the shared docs directory. */
  path: string
  /** File size in bytes. */
  size: number
  /** Last modification time (epoch ms). */
  mtime: number
}

export interface DocReadResult {
  path: string
  /** File body (may be truncated — see `truncated`). */
  text: string
  truncated: boolean
  size: number
}

export interface DocsLayout {
  /** Absolute shared docs directory (project root + docsDir). */
  sharedDir: string
  /** Absolute generated area (sharedDir/.dlab). */
  trackDir: string
  /** Docs directory relative to the project root. */
  relDir: string
}

export interface PromoteDocsInput {
  solutionId: string
  /** Copy the solution's local notes into `<shared>/local/<slug>/`. */
  includeLocal?: boolean
  /** Paths relative to the shared docs dir to overwrite from the solution's local notes. */
  promote?: string[]
  conclusion?: string
}

export interface PromoteDocsResult {
  /** Paths written into the shared docs directory. */
  sharedWrites: string[]
  /** Paths copied out of the solution's local notes. */
  localCopies: string[]
  /** The snapshot file written under `docs/.dlab/snapshots/`. */
  snapshot: string
  /** Shared-docs version commit created by this promotion (absent on failure). */
  version?: string
}

/** Read cap for one document body (guards against multi-MB log-like docs). */
const MAX_READ_BYTES = 512 * 1024

export class DocsService {
  constructor(private readonly deps: LabDeps) {}

  /** sha of the most recent shared-docs version commit (this process). */
  lastVersionCommit: string | null = null

  private get config() {
    return this.deps.config
  }

  /** Absolute shared docs directory (may not exist yet). */
  get sharedDir(): string {
    return resolve(this.config.projectRoot, this.config.docsDir)
  }

  /** Absolute generated area. */
  get trackDir(): string {
    return join(this.sharedDir, this.config.trackDir)
  }

  layout(): DocsLayout {
    return { sharedDir: this.sharedDir, trackDir: this.trackDir, relDir: this.config.docsDir }
  }

  /** Absolute path of one solution's doc link (`solutions/<slug>/local/docs`). */
  linkPathFor(solution: Pick<Solution, 'slug'>): string {
    return join(this.config.projectRoot, this.config.solutionsDir, solution.slug, this.config.docLinkPath)
  }

  // ── layout guarantees ───────────────────────────────────────────────────

  /**
   * Create the shared docs directory, its generated area and ignore rules.
   * Idempotent and safe on a fresh lab.
   */
  async ensureLayout(): Promise<DocsLayout> {
    mkdirSync(this.sharedDir, { recursive: true })
    mkdirSync(join(this.trackDir, 'snapshots'), { recursive: true })
    mkdirSync(join(this.trackDir, 'mirror'), { recursive: true })
    this.writeIfChanged(
      join(this.trackDir, '.gitignore'),
      ['# generated by dsh-lab — never commit derived document state', '*', '!.gitignore', ''].join('\n'),
    )
    this.seedIndex()
    return this.layout()
  }

  /**
   * Version the shared docs directory onto `refs/dsh/docs`, chained to the
   * previous snapshot. The directory lives in the project root (not inside a
   * worktree), so this is the only way it enters git history — and it means a
   * promoted document is reviewable and restorable like any commit.
   */
  async commitVersion(message: string): Promise<string | undefined> {
    if (!existsSync(this.sharedDir)) return undefined
    try {
      const sha = await this.deps.git.commitPathSnapshot({
        workTree: this.config.projectRoot,
        path: this.config.docsDir,
        refName: this.versionRef,
        message,
        parentRef: this.versionRef,
        exclude: this.config.trackDir,
      })
      this.lastVersionCommit = sha
      return sha
    } catch {
      // an un-versioned docs directory still works; versioning is additive
      return undefined
    }
  }

  /** The ref the shared docs history is kept under. */
  get versionRef(): string {
    return `${this.config.docsVersionRef}`
  }

  /** Log of the shared docs history (newest first). */
  async history(limit = 20): Promise<{ commit: string; message: string; at: number }[]> {
    try {
      const entries = await this.deps.git.logRef(this.versionRef, limit)
      return entries
    } catch {
      return []
    }
  }

  /**
   * Materialize `local/docs` inside a solution worktree.
   *
   * Why the link lives at `local/docs` rather than at the worktree root: the
   * path must be identical in EVERY solution worktree, so that one git tree
   * cannot mean two different things depending on who materialized it. The
   * link is therefore committed to the branch once and only ever points at
   * the project root's docs directory.
   */
  materialize(solution: Pick<Solution, 'slug'>): void {
    const worktree = resolve(this.config.projectRoot, this.config.solutionsDir, solution.slug)
    if (!existsSync(worktree)) return
    this.ensureLayout()
    const link = join(worktree, this.config.docLinkPath)
    mkdirSync(resolve(link, '..'), { recursive: true })
    // relative target computed from the link's own directory, so the link is
    // valid at any nesting depth of `docLinkPath`
    const target = relative(resolve(link, '..'), this.sharedDir) || '.'

    try {
      const existing = this.lstatOrNull(link)
      if (existing === null) {
        symlinkSync(target, link, 'dir')
        return
      }
      if (existing.isSymbolicLink() || existing.isDirectory()) {
        // Already materialized (link or a real dir made by hand) — the
        // content behind it is the root docs either way.
        if (this.readlinkSafe(link) === target) return
        rmSync(link, { recursive: true, force: true })
        symlinkSync(target, link, 'dir')
        return
      }
      // A regular file named `docs` — replace it with the link.
      rmSync(link, { force: true })
      symlinkSync(target, link, 'dir')
    } catch {
      /* a filesystem without symlinks degrades to "no link"; the docs
         directory itself is still reachable at its root path */
    }
  }

  /** Ensure `local/docs` exists in EVERY active solution worktree. */
  async repairLinks(): Promise<string[]> {
    const repaired: string[] = []
    const solutions = await this.deps.store.listSolutions()
    for (const solution of solutions) {
      if (solution.status !== 'active') continue
      const before = this.readlinkSafe(this.linkPathFor(solution))
      this.materialize(solution)
      if (this.readlinkSafe(this.linkPathFor(solution)) !== before) repaired.push(solution.slug)
    }
    return repaired
  }

  // ── reads ───────────────────────────────────────────────────────────────

  /** Every shared document, recursive, newest first (docs/.dlab excluded). */
  list(): DocEntry[] {
    const out: DocEntry[] = []
    this.walk(this.sharedDir, '', out)
    return out.sort((a, b) => b.mtime - a.mtime)
  }

  /** Read one shared document by its path relative to the docs directory. */
  read(relPath: string): DocReadResult {
    const abs = this.resolveInside(relPath)
    const stat = statSync(abs)
    const limit = Math.min(stat.size, MAX_READ_BYTES)
    const buffer = readFileSync(abs)
    const slice = buffer.subarray(0, limit)
    return {
      path: relPath,
      text: slice.toString('utf8'),
      truncated: stat.size > limit,
      size: stat.size,
    }
  }

  /** Whether a path currently exists under the shared docs directory. */
  exists(relPath: string): boolean {
    try {
      return existsSync(this.resolveInside(relPath))
    } catch {
      return false
    }
  }

  /** The generated state file describing the layout (docs/.dlab/state.json). */
  state(): Record<string, unknown> {
    const file = join(this.trackDir, 'state.json')
    try {
      return JSON.parse(readFileSync(file, 'utf8')) as Record<string, unknown>
    } catch {
      return {}
    }
  }

  // ── writes ──────────────────────────────────────────────────────────────

  /** Create or overwrite one shared document (used by init and by tools). */
  write(relPath: string, text: string): string {
    const abs = this.resolveInside(relPath)
    mkdirSync(resolve(abs, '..'), { recursive: true })
    writeFileSync(abs, text)
    this.stamp(relPath, text.length)
    return relPath
  }

  /**
   * Copy one document out of a solution worktree into the shared directory.
   * Used to promote a local note into shared knowledge.
   */
  copyFromSolution(solution: Solution, relPath: string, sharedPath?: string): string {
    const source = resolve(this.solutionDir(solution), relPath)
    const text = readFileSync(source, 'utf8')
    const target = sharedPath ?? relPath
    this.write(target, text)
    return target
  }

  /**
   * Promote a solution's results: mirror the local notes into
   * `docs/local/<slug>/` and write an immutable snapshot (path, sha, mtime)
   * under `docs/.dlab/snapshots/`.
   *
   * The snapshot is what survives archiving: removing a worktree never
   * deletes promoted knowledge.
   */
  async promoteSolution(input: PromoteDocsInput): Promise<PromoteDocsResult> {
    const solution = await this.requireSolution(input.solutionId)
    const result: PromoteDocsResult = { sharedWrites: [], localCopies: [], snapshot: '' }
    const worktree = this.solutionDir(solution)

    if (input.includeLocal !== false) {
      const localDirs = ['docs', 'notes', join('local', 'docs')].filter((d) => {
        if (d === this.config.docLinkPath) return false // the root link is not local
        return existsSync(join(worktree, d))
      })
      for (const dir of localDirs) {
        const files = this.walkFiles(join(worktree, dir))
        for (const file of files) {
          if (file.startsWith(this.config.trackDir)) continue
          // keep the source directory in the mirror path, so an archived
          // line's notes stay traceable to where they lived
          const rel = join('local', solution.slug, dir, file)
          const target = join(worktree, dir, file)
          this.write(rel, readFileSync(target, 'utf8'))
          result.localCopies.push(rel)
        }
      }
    }

    for (const sharedPath of input.promote ?? []) {
      for (const dir of ['docs', 'notes', join('local', 'docs')]) {
        const candidate = join(worktree, dir, sharedPath)
        if (existsSync(candidate)) {
          this.write(sharedPath, readFileSync(candidate, 'utf8'))
          result.sharedWrites.push(sharedPath)
          break
        }
      }
    }

    if (input.conclusion) {
      const rel = join('local', solution.slug, 'conclusion.md')
      this.write(rel, `# ${solution.slug}\n\n${input.conclusion}\n`)
      result.localCopies.push(rel)
    }

    result.snapshot = this.writeSnapshot(solution, result)
    result.version = await this.commitVersion(
      `[dsh-lab] docs: promote ${solution.slug}${input.conclusion ? ' (conclusion)' : ''}`,
    )
    return result
  }

  // ── internals ───────────────────────────────────────────────────────────

  private solutionDir(solution: Pick<Solution, 'slug'>): string {
    return resolve(this.config.projectRoot, this.config.solutionsDir, solution.slug)
  }

  private async requireSolution(idOrSlug: string): Promise<Solution> {
    const store = this.deps.store
    const found = (await store.getSolution(idOrSlug)) ?? (await store.getSolutionBySlug(idOrSlug))
    if (!found) throw new Error(`solution "${idOrSlug}" not found`)
    return found
  }

  /** Path-traversal guard: every doc path stays under the shared directory. */
  private resolveInside(relPath: string): string {
    const abs = resolve(this.sharedDir, relPath)
    const root = this.sharedDir
    if (abs !== root && !abs.startsWith(root + '/')) {
      throw new Error(`document path "${relPath}" escapes the docs directory`)
    }
    return abs
  }

  private walk(abs: string, rel: string, out: DocEntry[]): void {
    if (!existsSync(abs)) return
    for (const entry of readdirSync(abs, { withFileTypes: true })) {
      if (entry.name === '.dlab' && rel === '') continue
      if (entry.name.startsWith('.git')) continue
      const childRel = rel ? join(rel, entry.name) : entry.name
      const childAbs = join(abs, entry.name)
      if (entry.isDirectory()) {
        this.walk(childAbs, childRel, out)
      } else if (entry.isFile()) {
        const stat = statSync(childAbs)
        out.push({ path: childRel, size: stat.size, mtime: Math.round(stat.mtimeMs) })
      }
    }
  }

  private walkFiles(abs: string): string[] {
    const out: string[] = []
    const visit = (dir: string, rel: string): void => {
      for (const entry of readdirSync(dir, { withFileTypes: true })) {
        if (entry.name.startsWith('.')) continue
        const childRel = rel ? join(rel, entry.name) : entry.name
        const childAbs = join(dir, entry.name)
        if (entry.isDirectory()) visit(childAbs, childRel)
        else if (entry.isFile()) out.push(childRel)
      }
    }
    if (existsSync(abs)) visit(abs, '')
    return out
  }

  private writeSnapshot(solution: Solution, result: PromoteDocsResult): string {
    const stamp = new Date().toISOString().replace(/[:.]/g, '-')
    const rel = join(this.config.trackDir, 'snapshots', `${stamp}-${solution.slug}.json`)
    const body = {
      solution: solution.slug,
      solutionId: solution.id,
      headCommit: solution.headCommit,
      at: Date.now(),
      sharedWrites: result.sharedWrites,
      localCopies: result.localCopies,
    }
    const abs = join(this.sharedDir, rel)
    mkdirSync(resolve(abs, '..'), { recursive: true })
    writeFileSync(abs, JSON.stringify(body, null, 2))
    return rel
  }

  /** Record the layout + a cheap fingerprint in docs/.dlab/state.json. */
  private stamp(relPath: string, bytes: number): void {
    const file = join(this.trackDir, 'state.json')
    let current: Record<string, unknown> = {}
    try {
      current = JSON.parse(readFileSync(file, 'utf8')) as Record<string, unknown>
    } catch {
      /* first run */
    }
    const docs = (current.docs as Record<string, unknown> | undefined) ?? {}
    docs[relPath] = { bytes, at: Date.now() }
    const next = { ...current, docsDir: this.config.docsDir, docs }
    mkdirSync(this.trackDir, { recursive: true })
    writeFileSync(file, JSON.stringify(next, null, 2))
  }

  private seedIndex(): void {
    const index = join(this.sharedDir, 'README.md')
    if (existsSync(index)) return
    this.writeIfChanged(
      index,
      [
        '# Shared documents',
        '',
        'This directory is the project-wide source of truth. It lives at the',
        'project root and is carried by the `main` solution; every solution',
        'worktree reaches it through the link `local/docs`.',
        '',
        'Put here: project charter and goals, the current roadmap, baseline',
        'references from other projects, environment setup, and cross-cutting',
        'lessons. Per-experiment notes stay inside their solution and are',
        'promoted here (`lab_promote_docs`) once they are worth keeping.',
        '',
        '## Index',
        '',
        '_Add one line per document: `path — what it decides / records`._',
        '',
      ].join('\n'),
    )
  }

  private writeIfChanged(abs: string, text: string): void {
    try {
      if (existsSync(abs) && readFileSync(abs, 'utf8') === text) return
    } catch {
      /* fall through to the write */
    }
    mkdirSync(resolve(abs, '..'), { recursive: true })
    writeFileSync(abs, text)
  }

  private lstatOrNull(path: string): Stats | null {
    try {
      return lstatSync(path)
    } catch {
      return null
    }
  }

  private readlinkSafe(path: string): string | null {
    try {
      return readlinkSync(path)
    } catch {
      return null
    }
  }

  /**
   * The generated line a worktree-side report would use. The docs pillar is
   * rooted at the project root (not at a solution), so this is a constant-
   * relative path for every solution.
   */
  static linkTarget(docsDir: string, depth = 2): string {
    return join(...Array.from({ length: depth + 1 }, () => '..'), docsDir)
  }
}
